spring:
  datasource:
    #    type: ${spring.datasource.type}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${datasource.bcos3-node-master.url}
    username: ${datasource.bcos3-node-master.username}
    password: ${datasource.bcos3-node-master.password}
    initialSize: 10
    minIdle: 5
    maxActive: 30
  aop:
    proxy-target-class: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.webank.webase.node.mgr
  mapperLocations: classpath:mapper/*.xml

#log config
logging:
  config: classpath:log/log4j2.xml
  level:
    com.webank.webase.node.mgr: info

#constants
constant:
  ###http request
  # login's authorization whether enable, if false, default login as `admin` account
  # WARN!! disabled authorization is unsafe in public internet
  isUseSecurity: true
  # verification code expire time (s)
  verificationCodeMaxAge: 300
  # if disabled as false, code would be constant value
  # WARN!! disabled random verification code is unsafe in public internet
  enableVerificationCode: true
  # verification code constant value, only when enableVerificationCode is false works
  verificationCodeValue: "8888"
  # auth token code expire time (s)
  authTokenMaxAge: 3600
  ignoreCheckFront: /account/login,/account/pictureCheckCode,/login,/user/privateKey,/front/new,/front/refresh,/front/find,/config/version,/group/all/invalidIncluded,/swagger-ui.html,/account/register,/account/mail,/account/mail/*,/account/privacy
  ###front http request
  frontUrl: http://%1s:%2d/WeBASE-Front/%3s
  httpTimeOut: 15000
  contractDeployTimeOut: 30000
  maxRequestFail: 3
  sleepWhenHttpMaxFail: 60000

  ###common
  developerModeEnable: true
  deployedModifyEnable: true
  isDeleteInfo: true
  transRetainMax: 10000
  deleteInfoCron: "*/15 * * * * ?"
  statisticsTransDailyCron: "0 0/1 * * * ?"
  resetGroupListCycle: 600000
  groupInvalidGrayscaleValue: 1M    # y:year, M:month, d:day of month, h:hour, m:minute, n:forever valid
  notSupportFrontIp:

  ###application integration
  # app request timestamp timeout (ms)
  appRequestTimeOut: 300000
  appStatusCheckCycle: 3000

  ###block info (pulling data from chain)
  isBlockPullFromZero: false
  pullBlockInitCnts: 1000
  pullBlockSleepTime: 200
  pullBlockTaskFixedDelay: 30000
  blockRetainMax: 5000
  ###transaction monitor
  transMonitorTaskFixedRate: 60000  #How long does it take to start the next task after the end (second)
  analysisSleepTime: 200
  monitorInfoRetainMax: 10000
  isMonitorIgnoreUser: false
  isMonitorIgnoreContract: false
  # if abnormal contract, abnormal user reach the max count, stop monitor
  monitorUnusualMaxCount: 20
  ###alert mail monitor task interval: 5mins unit: ms
  auditMonitorTaskFixedDelay: 300000
  nodeStatusMonitorTaskFixedDelay: 60000  #must larger than @pullBlockTaskFixedDelay
  certMonitorTaskFixedDelay: 300000
  permitUrlArray: /account/login,/account/pictureCheckCode,/login,/user/privateKey/**,/config/encrypt,/config/auth,/config/version,/front/refresh,/api/*,/auth/base/available,/account/register,/account/mail,/account/mail/*,/account/privacy
  ###interval to async refresh group list locally
  resetGroupListInterval: 15000
  ###interval block statistic, unit: ms
  statBlockRetainMax: 100000
  statBlockFixedDelay: 10000
  statBlockPageSize: 20 # block stat data to pull in one time
  enableExternalFromBlock: true # enable record account and contract from block
  ###enable user register and mail second check
  enableRegisterMailCheck: false
  # SMTP服务用于发送验证码，默认端口为25，暂未支持SSL/TLS（若启用SMTP SSL或TLS则465或587端口）
  smtpHost: smtp.qq.com
  smtpPort: 25
  smtpUsername: "yourmail@qq.com"
  smtpPassword: "yourMailPassword"
  accountInfoAesKey: b1eab1c216de9746

  #### 1.4.0 visual deploy
  #### deployType 部署方式：
  # 0, 先使用 build_chain.sh 部署链并启用 WeBASE-Front 服务，然后手动添加前置;
  # 1, 使用可视化部署, 需要参考WeBASE文档填写下面参数
  deployType: 1
  #### if deployType = 0, ignore below properties ####
  # 镜像名
  dockerRepository: "webasepro/fisco-webase"
  # WeBASE-Sign 访问地址，供节点前置访问，不能填写localhost或127.0.0.1，填写nginx开放的签名服务地址
  webaseSignAddress: "http://192.168.1.48/sign3"
  # 可视化操作的后台超时时间 (unit: ms)，若机器较慢，可动态设置超时时间
  execDockerCheckTimeout: 55000
  execHostCheckTimeout: 55000
  execHostCheckPortTimeout: 50000
  execHostInitTimeout: 300000
  execHostConfigTimeout: 40000
  execBuildChainTimeout: 40000
  dockerRestartPeriodTime: 30000
  execShellTimeout: 600000
  execScpTimeout: 10000
  execAddNodeTimeout: 40000
  # runDockerSleepTime: 600000
  #### if deployType = 0, ignore upper properties ####


sdk:
  # 加密类型：0: 非国密;  1: 国密
  ## 可视化部署时，此配置将决定部署国密或非国密链
  ## 国密与非国密链的私钥、合约数据不兼容
  encryptType: 1

# executor config for async pulling data from chain
executor:
  corePoolSize: 10
  maxPoolSize: 20
  queueSize: 50
  threadNamePrefix: "node-mgr-async-"

# scheduler config for sync scheduled task
scheduler:
  poolSize: 30
  threadNamePrefix: "node-mgr-task-"
  awaitTerminationSeconds: 600
  waitForTasksToCompleteOnShutdown: true
